manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kenakofer
      url-base: https://github.com/kenakofer
      
  projects:
    - name: zmk
      remote: kenakofer
      revision: main
      import: app/west.yml
  self:
    path: config
